services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web-app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`skytezz.azhao.fr`)"
      - "traefik.http.routers.web.entrypoints=web"
      - "traefik.http.services.web.loadbalancer.server.port=80"
      - "traefik.http.routers.web.middlewares=redirect-to-https@docker"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.websecure.rule=Host(`skytezz.azhao.fr`)"
      - "traefik.http.routers.websecure.entrypoints=websecure"
      - "traefik.http.routers.websecure.tls=true"
      - "traefik.http.routers.websecure.tls.certresolver=myresolver"
    networks:
      - web

networks:
  web:
    external: true
